run: 1
mode: train
source: Art
target: Clipart
dataset: officehome

path:
   datasetroot: datasets/OfficeHome
   collectionroot: VisualSearch

data:
    annotation: concepts65.txt

network:
    model: KDDE_DDC
    model_weight: None
    backbone: ResNet50
    num_class: 65
    sup_model: ResNet50
    da_model: DDC
    sup_model_weight: None
    da_model_weight: None
    gpus: [0]

train:
    kdCT: False
    miCT: False
    lr: 0.005
    momentum: 0.9
    l2_decay: 5.e-4
    scheduler_epoch: 30
    scheduler_gamma: 0.1
    temperature: 1
    alpha: 10
    beta: 1
    epochs: 100
    batch_size: 32
    num_workers: 4
    log_interval: 10
    
test:
    batch_size: 64
    num_workers: 4


    
    
    
    


    
